server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9000}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: USER-SERVICE
          uri: http://user-service-svc
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: EVENTS-SERVICE
          uri: http://events-service-svc
          predicates:
            - Path=/events/**
          filters:
            - StripPrefix=1
#        - id: EVENTS-SERVICE
#          uri: http://events-service-svc:80
#          predicates:
#            - Path=/events/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: EVENTS-SERVICE
#                fallbackuri: forward:/eventsServiceFallBack

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

app:
  jwtCookieName: myplanet
  jwtSecret: myplanetsecret
  jwtExpirationMs: 86400000